### ISSUE TITLE
Onlink link down

### ISSUE THREAD

**Issue by skiphansen** [EpimetheusMusicPlayer/json_api_decrypter#2]
https://crypto.epimetheus.tk/ isn't resolving for me, is there an alternative link??

I've figured out how to get a plain text capture and I'm **VERY** interested in reverse engineering Pandor's playlists but I know nothing about Dart, I'm C programmer.

Are you still interested in Pandora?

**Comment by hacker1024** [comment]
Sorry for the delay - I've modernised this program and moved to a regular GitHub Pages URL.

**Comment by skiphansen** [comment]
Thanks the new link works.  I'll probably just use your https://github.com/EpimetheusMusicPlayer/pandora_mitm project. I hadn't discovered it yet when I opened this issue.
